services:
  development-client:
    container_name: development-client
    build:
      context: client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    restart: always
    environment:
      REACT_APP_PROXY: http://development-server:5000
    depends_on:
      - development-server

  development-server:
    container_name: development-server
    build:
      context: server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    restart: always
    environment: 
      NODE_ENV: development
      PG_HOST: development-database
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE: ${PG_DATABASE}
    depends_on:
      development-database:
        condition: service_healthy
        restart: true

  development-database:
    container_name: development-database
    image: postgres:alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DATABASE}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - ./data/development/pgdata:/var/lib/postgresql/data

  production:
    container_name: production
    build:
      context: .
    ports:
      - "${CLIENT_PORT:-3000}:3000"
    restart: unless-stopped
    volumes:
      - ./data/production:/app/data
    environment: 
      NODE_ENV: production
      PORT: 3000
      PG_HOST: production-database
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE: ${PG_DATABASE}
    depends_on:
      production-database:
        condition: service_healthy
        restart: true

  production-database:
    container_name: production-database
    image: postgres:alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DATABASE}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - ./data/production/pgdata/:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    hostname: pgadmin